# Default values for fft_boxing.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

job:
  name: []
  description: []
  restartPolicy: Never

ImpWCnet: 
  seed: 202211
  num_epoch: 100
  batch_size: 64
  lr0: 0.001
  lr_a: 0.001
  lr_b: 0.25
  momentum: 0.9
  w_decay: 0.0005
  lbl_sm: 0.01
  model: []
  wavelet: []
  dataset: []
  num_workers: 4
  task: []
  datadir: data/
  logdir: log/
  ptdir: pretrain/
  log_filename: []
  init_weights: 0
  resume_train: 0
  exp_label: default
  gpu: 0
  
storage:
  data: dataset-pvc
  results: log-pvc
  pretain: pretrain-pvc

image:
  registry: wcsng-36.nrp-nautilus.io

resources:
  limits:
    cpu: 6000m
    memory: 20Gi
    nvidia.com/gpu: 1
  requests:
    cpu: 4000m
    memory: 16Gi
    nvidia.com/gpu: 1

requiredGPU: []
# requiredGPU: 
# - NVIDIA-GeForce-GTX-1070
# - NVIDIA-GeForce-GTX-1080
# - Quadro-M4000
# - NVIDIA-A100-PCIE-40GB-MIG-2g.10gb
# - NVIDIA-GeForce-GTX-1080-Ti
# - NVIDIA-GeForce-RTX-2080-Ti
# - NVIDIA-TITAN-Xp
# - Tesla-T4
# - NVIDIA-GeForce-RTX-3090
# - NVIDIA-TITAN-RTX
# - NVIDIA-RTX-A5000
# - Quadro-RTX-6000
# - Tesla-V100-SXM2-32GB
# - NVIDIA-A40
# - NVIDIA-RTX-A6000
# - Quadro-RTX-8000